<a href="https://colab.research.google.com/github/boaca926-beep/Pytorch-Tutorials/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import torch

### TENSORS

* A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
* Similar to Numpy Arrays, but full or fun thins that make them work better on GPU's (vs regular CPU's).
* Default data type of folat32.
* More suitable for deep learning than a numpy array.

In [110]:
#!pip list

In [111]:
import torch
import numpy as np

### List

In [112]:
my_list = [[1,2,3,4,5],[7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [7, 8, 9, 10]]

### NUMPY ARRAY

In [113]:
np1 = np.random.rand(3,4)
np1

array([[0.60502833, 0.71408811, 0.27999145, 0.53449644],
       [0.92387957, 0.66466945, 0.40199486, 0.39331913],
       [0.30579069, 0.93304262, 0.55548565, 0.54669311]])

In [114]:
np1.shape

(3, 4)

In [115]:
np1.dtype

dtype('float64')

### Tensors

In [116]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.1049,  1.3981, -0.4176,  0.7686],
        [ 0.4621,  1.6255,  0.7472, -0.1790],
        [ 0.2458, -0.0301, -0.7136,  0.1612]])

In [117]:
tensor_2d.shape
#tensor_2d.dtype

torch.Size([3, 4])

In [118]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor out of numpy array

In [119]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6050, 0.7141, 0.2800, 0.5345],
        [0.9239, 0.6647, 0.4020, 0.3933],
        [0.3058, 0.9330, 0.5555, 0.5467]], dtype=torch.float64)

### Tensor operations

In [120]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape and View

In [121]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### Reshpe if we dont't know the number of iterms using -1

In [122]:
my_torch2 = torch.arange(15)
my_torch2


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [123]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [124]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# with reshape and view, they will update

In [126]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [128]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [129]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slices

In [130]:
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Grab a specific item

In [131]:
my_torch7[7]

tensor(7)

# Grab slice

In [132]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [133]:
my_torch8[:,1].shape

torch.Size([5])

# Retrun column

In [134]:
my_torch8[:,1:].shape

torch.Size([5, 1])

### Tenor math operations

In [135]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [136]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [137]:
# Addition longhand

In [138]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [139]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [140]:
# Sub funciton
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [141]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [142]:
# Multi function
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [143]:
# Divistion
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [144]:
# Division function
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [145]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [146]:
# Remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [147]:
# Exponents
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [148]:
# Another way of writing longhand

tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [149]:
# Reassignment_
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [150]:
tensor_a

tensor([1, 2, 3, 4])

In [151]:
#tensor_a = tensor_a + tensor_b
tensor_a

tensor([1, 2, 3, 4])

In [152]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [153]:
tensor_a

tensor([ 6,  8, 10, 12])